### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by justdaver** [jjneely/statsrelay#3]
I've run into a strange problem recently which I did not have before and am slowly loosing my mind trying to get to the bottom of it :) 

This is my test environment (using RHEL 7):

I'm running statsrelay with the following command options on serverx (2 backend statsd hosts):

```
statsrelay -bind=10.0.0.1 -port=12001 -prefix=serverx -verbose=true 10.0.0.10:12000 10.0.0.20:12000
```

```
2015/05/12 15:11:59 Listening on 10.0.0.1:12001
2015/05/12 15:11:59 Setting socket read buffer size to: 212992
2015/05/12 15:11:59 Rock and Roll!
```

Then on my test client I'm sending it a statsd metric using netcat like so:

```
echo "a.b.c:1|c" | nc -w 1 -u 10.0.0.1 12001
```

As soon as the metric hits serverx on 12001 (UDP), statsrelay crashes and the following appears in the console:

```
panic: runtime error: slice bounds out of range

goroutine 27 [running]:
runtime.panic(0x53b7c0, 0x624c6f)
        /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
main.getMetricName(0xc208380011, 0x0, 0xfffef, 0x0, 0x0)
        /home/dave/statsrelay/statsrelay.go:79 +0xa6
main.handleBuff(0xc208380000, 0x11, 0x100000)
        /home/dave/statsrelay/statsrelay.go:139 +0x1ea
created by main.runServer
        /home/dave/statsrelay/statsrelay.go:276 +0x1db

goroutine 16 [select]:
main.runServer(0x7fffec2bc801, 0x7, 0x2ee1)
        /home/dave/statsrelay/statsrelay.go:273 +0x2db
main.main()
        /home/dave/statsrelay/statsrelay.go:341 +0x694

goroutine 19 [finalizer wait]:
runtime.park(0x416570, 0x6283d8, 0x626f09)
        /usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x6283d8, 0x626f09)
        /usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        /usr/lib/golang/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/lib/golang/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7fc7fa7be708, 0x72, 0x0)
        /usr/lib/golang/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802c060, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20802c060, 0x0, 0x0)
        /usr/lib/golang/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc20802c000, 0xc208480000, 0x100000, 0x100000, 0x0, 0x7fc7fa7bd2b8, 0xb)
        /usr/lib/golang/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc20803a018, 0xc208480000, 0x100000, 0x100000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/pkg/net/net.go:122 +0xe7
main.readUDP(0x7fffec2bc801, 0x7, 0x2ee1, 0xc208054000)
        /home/dave/statsrelay/statsrelay.go:235 +0x6fa
created by main.runServer
        /home/dave/statsrelay/statsrelay.go:270 +0x132
```

Any help/pointers would be greatly appreciated! Most likely I've completely missed the boat here and doing something wrong, have been stuck with this issue for a couple hours now!

Thanks!
Dave

**Comment by jjneely** [comment]
Before the return statement on line 79 add a lines like this:

```
log.Printf("Metric data: %s", string(metric))
log.Printf("Metric name length: %d", length)
```

This will log for each metric received...so testing only.  But that will show what the misbehaving function is seeing and what the value of length is.  Which should show us a little bit more of the issue.

Is that something you are comfortable with?

**Comment by jjneely** [comment]
Ah, this is the trailing newline that the echo command is adding to the string.  With echo -n this doesn't happen.  Not saying this shouldn't be fixed...but that's the cause.

**Comment by jjneely** [comment]
I believe that should fix things.

**Comment by justdaver** [comment]
Success! Thanks Jack that fixed it, much appreciated :)

```
2015/05/13 09:04:18 Procssed 1 metrics. Running total: 1. Metrics/sec: 0
```
