### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by justdaver** [jjneely/statsrelay#7]
Hey Guys,

I'm facing a bit of a strange problem at the moment, a statsrelay process is crashing at one of our sites for some reason. I've run the daemon in verbose mode and this is the error message just after it crashes.

Could this be the result of a malformed metric name received?

```
2015/10/27 12:15:01 Procssed 11261 metrics. Running total: 4006453. Metrics/sec: 14411

panic: runtime error: slice bounds out of range

goroutine 384 [running]:
runtime.panic(0x53b7c0, 0x624c6f)
        /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
main.getMetricName(0xc208312cbb, 0x30, 0xbb345, 0x0, 0x0)
        /admin/golang/statsrelay/statsrelay.go:79 +0xa6
main.handleBuff(0xc2082ce000, 0xcceb5, 0x100000)
        /admin/golang/statsrelay/statsrelay.go:144 +0x9d8
created by main.runServer
        /admin/golang/statsrelay/statsrelay.go:281 +0x1db

goroutine 16 [select]:
main.runServer(0x7fff8c1a06b7, 0xc, 0x2ee1)
        /admin/golang/statsrelay/statsrelay.go:278 +0x2db
main.main()
        /admin/golang/statsrelay/statsrelay.go:346 +0x694

goroutine 19 [finalizer wait, 4 minutes]:
runtime.park(0x416580, 0x6283d8, 0x626f09)
        /usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x6283d8, 0x626f09)
        /usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 4 minutes]:
os/signal.loop()
        /usr/lib/golang/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/lib/golang/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7fd668027730, 0x72, 0x0)
        /usr/lib/golang/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802c220, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20802c220, 0x0, 0x0)
        /usr/lib/golang/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc20802c1c0, 0xc20846fd3f, 0xfc2c1, 0xfc2c1, 0x0, 0x7fd6680262b8, 0xb)
        /usr/lib/golang/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc20803c028, 0xc20846fd3f, 0xfc2c1, 0xfc2c1, 0x4d, 0x0, 0x0)
        /usr/lib/golang/src/pkg/net/net.go:122 +0xe7
main.readUDP(0x7fff8c1a06b7, 0xc, 0x2ee1, 0xc208070000)
        /admin/golang/statsrelay/statsrelay.go:240 +0x6fa
created by main.runServer
        /admin/golang/statsrelay/statsrelay.go:275 +0x132
```

**Comment by justdaver** [comment]
Sorry guys, my bad. This was an old bug. I compiled the latest version and it's not crashing any more. :)
