### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by justdaver** [jjneely/statsrelay#8]
Hi Guys,

For some reason I've noticed the statsrelay processes for one of our sites is crashing every 10-20 minutes, this is the error:

```
panic: runtime error: index out of range

goroutine 6 [running]:
main.readUDP(0x7fffc2e446b9, 0xc, 0x2ee1, 0xc2080640c0)
        /admin/downloads/statsrelay/latest/golang/statsrelay/statsrelay.go:276 +0x9a2
created by main.runServer
        /admin/downloads/statsrelay/latest/golang/statsrelay/statsrelay.go:309 +0x174

goroutine 1 [select]:
main.runServer(0x7fffc2e446b9, 0xc, 0x2ee1)
        /admin/downloads/statsrelay/latest/golang/statsrelay/statsrelay.go:312 +0x396
main.main()
        /admin/downloads/statsrelay/latest/golang/statsrelay/statsrelay.go:382 +0x762

goroutine 5 [syscall, 3 minutes]:
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35
```

Has anyone come across this problem before?

Thanks,
Dave

**Comment by jjneely** [comment]
I think so.  Make sure you are running the latest version from Git.

I really need to actually tag a new release.

**Comment by justdaver** [comment]
Sorry guys for the late response here!

I've compiled the latest version with golang 1.5.2 but still experiencing the same problem.

For reference this is how we're running the statsrelay process (there are 3 backend statsd servers):

```
statsrelay -bind=10.0.0.100 -port=12001 -prefix="stats.statsrelay1" 10.0.0.1:12000:1 \
10.0.0.2:12000:2667 10.0.0.3:12000:5333 10.0.0.1:12000:7999 10.0.0.2:12000:10665 \
10.0.0.3:12000:13331 10.0.0.1:12000:15997 10.0.0.2:12000:18663 10.0.0.3:12000:21329 \
10.0.0.1:12000:23995 10.0.0.2:12000:26661 10.0.0.3:12000:29327 10.0.0.1:12000:31993 \
10.0.0.2:12000:34659 10.0.0.3:12000:37325 10.0.0.1:12000:39991 10.0.0.2:12000:42657 \
10.0.0.3:12000:45323 10.0.0.1:12000:47989 10.0.0.2:12000:50655 10.0.0.3:12000:53321 \
10.0.0.1:12000:55987 10.0.0.2:12000:58653 10.0.0.3:12000:61319
```

**Comment by jjneely** [comment]
Take a look at the issue-8 branch.  https://github.com/jjneely/statsrelay/tree/issue-8

That has the fix for what I think you are hitting.

**Comment by justdaver** [comment]
Thanks Jack, I've compiled the issue-8 branch and so far haven't had a crash in a few hours so looks like that fix worked perfectly :)
